<?php

namespace Database\Seeders;

use App\Models\SubSubCategory;
use Illuminate\Database\Seeder;

class SubSubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // SubSubCategory::truncate();

        // 3er nivel de categorías
        if (SubSubCategory::count() == 0) {
            SubSubCategory::insert([

                // Literatura - temática
                ['name' => 'Arte', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Autoayuda', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Autobiográficos', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Aventuras', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Cocina', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Comic', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Contemporáneo', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Científicos', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Cuentos', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Culto', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Deporte', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Drama', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Economía', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Empresa', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Ensayo', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Erótica', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Espiritualidad', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Ficción', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Filología', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Filosofía', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Guerra', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Humor', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Idiomas', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Juvenil', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Manualidades', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Marketing', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Medicina', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Microrrelatos', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Música', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Novela', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Novela Histórica', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Novela negra', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Novelas Románticas', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Política', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Psicología', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Religión', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Salud', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Sociedad', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Suspense', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Técnicos', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Viajes', 'category_id' => 1, 'sub_category_id' => 1],
                ['name' => 'Videojuegos', 'category_id' => 1, 'sub_category_id' => 1],

                // Literatura - Idioma
                ['name' => 'Español', 'category_id' => 1, 'sub_category_id' => 2],
                ['name' => 'Inglés', 'category_id' => 1, 'sub_category_id' => 2],
                ['name' => 'Francés', 'category_id' => 1, 'sub_category_id' => 2],

                // Literatura - Material
                ['name' => 'Bolsillo', 'category_id' => 1, 'sub_category_id' => 3],
                ['name' => 'Encuadernación de Lujo', 'category_id' => 1, 'sub_category_id' => 3],
                ['name' => 'Tapa dura', 'category_id' => 1, 'sub_category_id' => 3],
                ['name' => 'Tapa Blanda', 'category_id' => 1, 'sub_category_id' => 3],


                // -------------
                // Pintura
                // ------------

                // pintura - Temática
                ['name' => 'Abstracto', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Autorretrato', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Animal', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Bodegón', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Concept', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Desnudo', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Fantasía', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Floral', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Futurista', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Historia', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Marina', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Naturaleza', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Paisaje', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Pasado', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Política', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Pop', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Religioso', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Retrato', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Urbano', 'category_id' => 2, 'sub_category_id' => 4],
                ['name' => 'Otras temáticas', 'category_id' => 2, 'sub_category_id' => 4],

                // pintura - estilo
                ['name' => 'Abstracto', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Barroco', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Bizantino', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Clásico', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Contemporáneo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Cubismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Expresionismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Fauvismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Figurativo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Flamenco', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Futurismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Geométrico', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Gótico', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Impresionismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Luminismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Manierismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Medieval', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Metafísico', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Minimalista', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Moderno', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Naif', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Nuevo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Oriental', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Pop Art', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Positivismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Puntillismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Realismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Renacentista', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Rococo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Románico', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Simbólico', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Surrealismo', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Vintage', 'category_id' => 2, 'sub_category_id' => 5],
                ['name' => 'Otro Estilo', 'category_id' => 2, 'sub_category_id' => 5],

                // Pintura - técnica
                ['name' => 'Acrílico', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Acuarela', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Aerosol', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Cera', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Collage', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Esmalte', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Grabado', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Graffiti', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Laca', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Lápiz', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Litografía', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Óleo', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Pigmentos', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Pastel', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Pintura', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Pluma', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Resina', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Serigrafía', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Tempera', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Textil', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Tinta', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Tiza', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Vinilo', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Tierra', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Yeso', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Metales', 'category_id' => 2, 'sub_category_id' => 6],
                ['name' => 'Otras técnicas', 'category_id' => 2, 'sub_category_id' => 6],

                // -------------
                // Escultura
                // -------------

                // Escultura - temática
                ['name' => 'Otras técnicas', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Abstracto', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Animal', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Autorretrato', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Bodegón', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Concept', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Desnudo', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Fantasía', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Floral', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Futurista', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Historia', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Marina', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Naturaleza', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Paisaje', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Pasado', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Política', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Pop', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Religioso', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Retrato', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Urbano', 'category_id' => 3, 'sub_category_id' => 7],
                ['name' => 'Otras temática', 'category_id' => 3, 'sub_category_id' => 7],

                // Escultura- estilo
                ['name' => 'Exterior', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Interior', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Iluminación', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Pared', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Techo', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Arquitectónica', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Relieve', 'category_id' => 3, 'sub_category_id' => 8],
                ['name' => 'Suspendida', 'category_id' => 3, 'sub_category_id' => 8],

                // Escultura- Material
                ['name' => 'Acero ', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Acero Corten', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Acero Inoxidable', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Aluminio', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Arcilla', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Bronce', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Cartón', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Cemento ', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Cristal', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Espejo', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Hierro', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Hojalata', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Hueso', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Luz', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Luz Led', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Madera', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Mármol', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Mosaik', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Neón', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Papel', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Perlas', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Piedra', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Piel', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Plástico', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Plexiglás', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Resina', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Taxidermia', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Terracota', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Textil', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Yeso', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Zinc', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Oro', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Plata', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Corcho', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Cartón', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Fluido', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Plasma', 'category_id' => 3, 'sub_category_id' => 9],
                ['name' => 'Otros Materiales', 'category_id' => 3, 'sub_category_id' => 9],

                // -------------
                // Dibujo
                // -------------

                // dibujo - temática
                ['name' => 'Abstracto', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Animal', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Autorretrato', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Bodegón', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Concept', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Desnudo', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Fantasía', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Floral', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Futurista', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Historia', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Marina', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Naturaleza', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Paisaje', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Pasado', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Política', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Pop', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Religioso', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Retrato', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Urbano', 'category_id' => 4, 'sub_category_id' => 10],
                ['name' => 'Otras temáticas', 'category_id' => 4, 'sub_category_id' => 10],

                // dibujo - estilo
                ['name' => 'Abstracto', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Barroco', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Bizantino', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Clásico', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Contemporáneo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Cubismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Expresionismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Fauvismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Figurativo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Flamenco', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Futurismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Geométrico', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Gótico', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Impresionismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Luminismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Manierismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Medieval', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Metafísico', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Minimalista', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Moderno', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Naif', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Nuevo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Oriental', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Otros Tipos de Estilo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Pop Art', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Positivismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Puntillismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Realismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Renacentista', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Rococo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Románico', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Simbólico', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Surrealismo', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Vintage', 'category_id' => 4, 'sub_category_id' => 11],
                ['name' => 'Otros Tipos de Estilo', 'category_id' => 4, 'sub_category_id' => 11],

                // Dibujo - técnica
                ['name' => 'Arena', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Carboncillo', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Fieltro', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Grabado', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Grafito', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Impresión Laser', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Lápiz', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Lápiz Color', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Monotiopia', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Otras Técnicas', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Pastel', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Pluma', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Relieve', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Serigrafía', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Tinta', 'category_id' => 4, 'sub_category_id' => 12],
                ['name' => 'Tiza', 'category_id' => 4, 'sub_category_id' => 12],

                // --------------
                // Fotografía
                // --------------

                // fotografía - temática
                ['name' => 'Abstracto', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Animal', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Autorretrato', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Bodegón', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Concept', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Desnudo', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Fantasía', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Floral', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Futurista', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Historia', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Marina', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Naturaleza', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Paisaje', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Pasado', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Política', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Pop', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Religioso', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Retrato', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Urbano', 'category_id' => 5, 'sub_category_id' => 13],
                ['name' => 'Otras temática', 'category_id' => 5, 'sub_category_id' => 13],

                // fotografía - estilo
                ['name' => 'Blanco y Negro', 'category_id' => 5, 'sub_category_id' => 14],
                ['name' => 'Color', 'category_id' => 5, 'sub_category_id' => 14],
                ['name' => 'Composición Digital', 'category_id' => 5, 'sub_category_id' => 14],
                ['name' => 'Panorámica', 'category_id' => 5, 'sub_category_id' => 14],
                ['name' => 'Sepia', 'category_id' => 5, 'sub_category_id' => 14],
                ['name' => 'Otro Estilo', 'category_id' => 5, 'sub_category_id' => 14],

                // fotografía - técnica
                ['name' => 'Digital ', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Física', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Compuesta', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Litografía', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Clave alta', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Clave baja', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Derechear el histograma', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fotografía infrarroja', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Larga exposición diurna', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Agua con efecto seda', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Barrido de movimiento', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Larga exposición nocturna', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fotografía de estrellas', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fotografiar la Vía Láctea', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Lightpainting', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fotografiar estelas de luz', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Alta velocidad', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Gota de agua', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Apertura de diafragma', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Bokeh', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Hiperfocal', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Otras técnicas fotográficas', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Zooming', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Bracketing u horquillado', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'HDR', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fotografía de humo', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fondo blanco', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fondo negro', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Time lapse', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Edición', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Desaturado selectivo', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Método Brenizer', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Fotografía Fine Art', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Multiexposición en Photoshop', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Efecto Orton', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Doble exposición', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Efecto Adamski', 'category_id' => 5, 'sub_category_id' => 15],
                ['name' => 'Otras técnicas fotográficas', 'category_id' => 5, 'sub_category_id' => 15],

                // ------------------------
                // Artesanía y Manualidades
                // ------------------------

                // artesanía - temática
                ['name' => 'Abstracto', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Animal', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Autorretrato', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Bodegón', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Concept', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Desnudo', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Fantasía', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Floral', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Futurista', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Historia', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Marina', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Naturaleza', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Paisaje', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Pasado', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Política', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Pop', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Religioso', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Retrato', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Urbano', 'category_id' => 6, 'sub_category_id' => 16],
                ['name' => 'Otras temática', 'category_id' => 6, 'sub_category_id' => 16],

                // artesanía - material
                ['name' => 'Origami o Papiroflexia', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Jabones', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Fieltro', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Goma EVA', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Pasta de sal', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Joyas', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Juegos y ', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Juguetes', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Perfumes', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Punto de Cruz', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Croché', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Ganchillo', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Camisetas', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Pañuelos', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Figuras', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Corcho', 'category_id' => 6, 'sub_category_id' => 17],
                ['name' => 'Velas', 'category_id' => 6, 'sub_category_id' => 17],

                // --------------------
                // Libros
                // --------------------

                // libros - temática
                ['name' => 'Arte', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Autoayuda', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Autobiográficos', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Aventuras', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Cocina', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Comic', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Contemporáneo', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Científicos', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Cuentos', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Culto', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Deporte', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Drama', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Economía', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Empresa', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Ensayo', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Erótica', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Espiritualidad', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Ficción', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Filología', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Guerra', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Humor', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Idiomas', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Juvenil', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Manualidades', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Marketing', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Medicina', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Microrrelatos', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Música', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Novela', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Novela Histórica', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Novela negra', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Novelas Románticas', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Política', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Psicología y Pedagogía', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Religión ', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Salud', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Sociedad', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Suspense', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Técnicos', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Viajes', 'category_id' => 7, 'sub_category_id' => 18],
                ['name' => 'Videojuegos', 'category_id' => 7, 'sub_category_id' => 18],

                // libros - idioma
                ['name' => 'Español ', 'category_id' => 7, 'sub_category_id' => 19],
                ['name' => 'Inglés', 'category_id' => 7, 'sub_category_id' => 19],
                ['name' => 'Francés ', 'category_id' => 7, 'sub_category_id' => 19],
                ['name' => 'Otros Idiomas', 'category_id' => 7, 'sub_category_id' => 19],

                // libros - material
                ['name' => 'Bolsillo', 'category_id' => 7, 'sub_category_id' => 20],
                ['name' => 'Encuadernación de Lujo', 'category_id' => 7, 'sub_category_id' => 20],
                ['name' => 'Tapa dura', 'category_id' => 7, 'sub_category_id' => 20],
                ['name' => 'Tapa Blanda', 'category_id' => 7, 'sub_category_id' => 20],
            ]);
        }
    }
}
